/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.vfs.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SharingLinksRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.vfs.jooq.tables.records.SharingLinksRecord> implements org.jooq.Record11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, org.joda.time.DateTime, org.joda.time.DateTime, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 132577967;

	/**
	 * Setter for <code>vfs.sharing_links.sharing_link_id</code>.
	 */
	public void setSharingLinkId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.sharing_link_id</code>.
	 */
	public java.lang.String getSharingLinkId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>vfs.sharing_links.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>vfs.sharing_links.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>vfs.sharing_links.link_type</code>.
	 */
	public void setLinkType(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.link_type</code>.
	 */
	public java.lang.String getLinkType() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>vfs.sharing_links.store_id</code>.
	 */
	public void setStoreId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.store_id</code>.
	 */
	public java.lang.Integer getStoreId() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>vfs.sharing_links.file_path</code>.
	 */
	public void setFilePath(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.file_path</code>.
	 */
	public java.lang.String getFilePath() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>vfs.sharing_links.file_hash</code>.
	 */
	public void setFileHash(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.file_hash</code>.
	 */
	public java.lang.String getFileHash() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>vfs.sharing_links.created_on</code>.
	 */
	public void setCreatedOn(org.joda.time.DateTime value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.created_on</code>.
	 */
	public org.joda.time.DateTime getCreatedOn() {
		return (org.joda.time.DateTime) getValue(7);
	}

	/**
	 * Setter for <code>vfs.sharing_links.expires_on</code>.
	 */
	public void setExpiresOn(org.joda.time.DateTime value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.expires_on</code>.
	 */
	public org.joda.time.DateTime getExpiresOn() {
		return (org.joda.time.DateTime) getValue(8);
	}

	/**
	 * Setter for <code>vfs.sharing_links.auth_mode</code>.
	 */
	public void setAuthMode(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.auth_mode</code>.
	 */
	public java.lang.String getAuthMode() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>vfs.sharing_links.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>vfs.sharing_links.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, org.joda.time.DateTime, org.joda.time.DateTime, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, org.joda.time.DateTime, org.joda.time.DateTime, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.SHARING_LINK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.LINK_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.STORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.FILE_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.FILE_HASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field8() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field9() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.EXPIRES_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.AUTH_MODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getSharingLinkId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getLinkType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getStoreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getFilePath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getFileHash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value8() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value9() {
		return getExpiresOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getAuthMode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value1(java.lang.String value) {
		setSharingLinkId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value2(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value3(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value4(java.lang.String value) {
		setLinkType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value5(java.lang.Integer value) {
		setStoreId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value6(java.lang.String value) {
		setFilePath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value7(java.lang.String value) {
		setFileHash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value8(org.joda.time.DateTime value) {
		setCreatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value9(org.joda.time.DateTime value) {
		setExpiresOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value10(java.lang.String value) {
		setAuthMode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord value11(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SharingLinksRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.String value6, java.lang.String value7, org.joda.time.DateTime value8, org.joda.time.DateTime value9, java.lang.String value10, java.lang.String value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SharingLinksRecord
	 */
	public SharingLinksRecord() {
		super(com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS);
	}

	/**
	 * Create a detached, initialised SharingLinksRecord
	 */
	public SharingLinksRecord(java.lang.String sharingLinkId, java.lang.String domainId, java.lang.String userId, java.lang.String linkType, java.lang.Integer storeId, java.lang.String filePath, java.lang.String fileHash, org.joda.time.DateTime createdOn, org.joda.time.DateTime expiresOn, java.lang.String authMode, java.lang.String password) {
		super(com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS);

		setValue(0, sharingLinkId);
		setValue(1, domainId);
		setValue(2, userId);
		setValue(3, linkType);
		setValue(4, storeId);
		setValue(5, filePath);
		setValue(6, fileHash);
		setValue(7, createdOn);
		setValue(8, expiresOn);
		setValue(9, authMode);
		setValue(10, password);
	}
}
