/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.vfs.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoresRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Short, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1623146074;

	/**
	 * Setter for <code>vfs.stores.store_id</code>.
	 */
	public void setStoreId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vfs.stores.store_id</code>.
	 */
	public java.lang.Integer getStoreId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>vfs.stores.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vfs.stores.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>vfs.stores.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vfs.stores.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>vfs.stores.built_in</code>.
	 */
	public void setBuiltIn(java.lang.Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vfs.stores.built_in</code>.
	 */
	public java.lang.Short getBuiltIn() {
		return (java.lang.Short) getValue(3);
	}

	/**
	 * Setter for <code>vfs.stores.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>vfs.stores.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>vfs.stores.uri</code>.
	 */
	public void setUri(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>vfs.stores.uri</code>.
	 */
	public java.lang.String getUri() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>vfs.stores.parameters</code>.
	 */
	public void setParameters(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>vfs.stores.parameters</code>.
	 */
	public java.lang.String getParameters() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Short, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Short, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.vfs.jooq.tables.Stores.STORES.STORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.vfs.jooq.tables.Stores.STORES.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.vfs.jooq.tables.Stores.STORES.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field4() {
		return com.sonicle.webtop.vfs.jooq.tables.Stores.STORES.BUILT_IN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.vfs.jooq.tables.Stores.STORES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.vfs.jooq.tables.Stores.STORES.URI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.vfs.jooq.tables.Stores.STORES.PARAMETERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getStoreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value4() {
		return getBuiltIn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getUri();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getParameters();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoresRecord value1(java.lang.Integer value) {
		setStoreId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoresRecord value2(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoresRecord value3(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoresRecord value4(java.lang.Short value) {
		setBuiltIn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoresRecord value5(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoresRecord value6(java.lang.String value) {
		setUri(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoresRecord value7(java.lang.String value) {
		setParameters(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoresRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Short value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StoresRecord
	 */
	public StoresRecord() {
		super(com.sonicle.webtop.vfs.jooq.tables.Stores.STORES);
	}

	/**
	 * Create a detached, initialised StoresRecord
	 */
	public StoresRecord(java.lang.Integer storeId, java.lang.String domainId, java.lang.String userId, java.lang.Short builtIn, java.lang.String name, java.lang.String uri, java.lang.String parameters) {
		super(com.sonicle.webtop.vfs.jooq.tables.Stores.STORES);

		setValue(0, storeId);
		setValue(1, domainId);
		setValue(2, userId);
		setValue(3, builtIn);
		setValue(4, name);
		setValue(5, uri);
		setValue(6, parameters);
	}
}
