/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.vfs.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stores implements java.io.Serializable {

	private static final long serialVersionUID = -1457966727;

	private java.lang.Integer storeId;
	private java.lang.String  domainId;
	private java.lang.String  userId;
	private java.lang.Short   builtIn;
	private java.lang.String  name;
	private java.lang.String  uri;
	private java.lang.String  parameters;
	private java.lang.String  provider;

	public Stores() {}

	public Stores(
		java.lang.Integer storeId,
		java.lang.String  domainId,
		java.lang.String  userId,
		java.lang.Short   builtIn,
		java.lang.String  name,
		java.lang.String  uri,
		java.lang.String  parameters,
		java.lang.String  provider
	) {
		this.storeId = storeId;
		this.domainId = domainId;
		this.userId = userId;
		this.builtIn = builtIn;
		this.name = name;
		this.uri = uri;
		this.parameters = parameters;
		this.provider = provider;
	}

	public java.lang.Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(java.lang.Integer storeId) {
		this.storeId = storeId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.Short getBuiltIn() {
		return this.builtIn;
	}

	public void setBuiltIn(java.lang.Short builtIn) {
		this.builtIn = builtIn;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getUri() {
		return this.uri;
	}

	public void setUri(java.lang.String uri) {
		this.uri = uri;
	}

	public java.lang.String getParameters() {
		return this.parameters;
	}

	public void setParameters(java.lang.String parameters) {
		this.parameters = parameters;
	}

	public java.lang.String getProvider() {
		return this.provider;
	}

	public void setProvider(java.lang.String provider) {
		this.provider = provider;
	}
}
