/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.vfs.jooq;

/**
 * Convenience access to all tables in vfs
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table vfs.sharing_links
	 */
	public static final com.sonicle.webtop.vfs.jooq.tables.SharingLinks SHARING_LINKS = com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS;

	/**
	 * The table vfs.stores
	 */
	public static final com.sonicle.webtop.vfs.jooq.tables.Stores STORES = com.sonicle.webtop.vfs.jooq.tables.Stores.STORES;
}
