/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.vfs.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vfs extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 324494207;

	/**
	 * The reference instance of <code>vfs</code>
	 */
	public static final Vfs VFS = new Vfs();

	/**
	 * No further instances allowed
	 */
	private Vfs() {
		super("vfs");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			com.sonicle.webtop.vfs.jooq.Sequences.SEQ_IDENTITIES,
			com.sonicle.webtop.vfs.jooq.Sequences.SEQ_STORES);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.sonicle.webtop.vfs.jooq.tables.SharingLinks.SHARING_LINKS,
			com.sonicle.webtop.vfs.jooq.tables.Stores.STORES);
	}
}
