/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.vfs.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stores extends org.jooq.impl.TableImpl<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord> {

	private static final long serialVersionUID = -218487705;

	/**
	 * The reference instance of <code>vfs.stores</code>
	 */
	public static final com.sonicle.webtop.vfs.jooq.tables.Stores STORES = new com.sonicle.webtop.vfs.jooq.tables.Stores();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord> getRecordType() {
		return com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord.class;
	}

	/**
	 * The column <code>vfs.stores.store_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord, java.lang.Integer> STORE_ID = createField("store_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>vfs.stores.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>vfs.stores.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>vfs.stores.built_in</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord, java.lang.Short> BUILT_IN = createField("built_in", org.jooq.impl.SQLDataType.SMALLINT.defaulted(true), this, "");

	/**
	 * The column <code>vfs.stores.name</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>vfs.stores.uri</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord, java.lang.String> URI = createField("uri", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * The column <code>vfs.stores.parameters</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord, java.lang.String> PARAMETERS = createField("parameters", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>vfs.stores.provider</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord, java.lang.String> PROVIDER = createField("provider", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>vfs.stores</code> table reference
	 */
	public Stores() {
		this("stores", null);
	}

	/**
	 * Create an aliased <code>vfs.stores</code> table reference
	 */
	public Stores(java.lang.String alias) {
		this(alias, com.sonicle.webtop.vfs.jooq.tables.Stores.STORES);
	}

	private Stores(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord> aliased) {
		this(alias, aliased, null);
	}

	private Stores(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.vfs.jooq.Vfs.VFS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.vfs.jooq.Keys.IDENTITY_STORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord> getPrimaryKey() {
		return com.sonicle.webtop.vfs.jooq.Keys.STORES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.vfs.jooq.tables.records.StoresRecord>>asList(com.sonicle.webtop.vfs.jooq.Keys.STORES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.vfs.jooq.tables.Stores as(java.lang.String alias) {
		return new com.sonicle.webtop.vfs.jooq.tables.Stores(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.vfs.jooq.tables.Stores rename(java.lang.String name) {
		return new com.sonicle.webtop.vfs.jooq.tables.Stores(name, null);
	}
}
